version: '3'

services:
  redis_persistent:
    container_name: "redis_persistent"
    image: redis:6-alpine
    restart: always
    ports:
      - 6389:6379
    entrypoint:
      "redis-server --appendonly yes"